---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://hooks.slack.com/services/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
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/free-credit-report
  label: Free Credit Report
  create: all
  match: "**/*"
  templates:
  - credit-report-guide
- type: directory
  path: content/mortgages
  label: Mortgages
  create: all
  match: "**/*"
  templates:
  - mortgages-guide
- type: directory
  path: content/credit-cards
  label: Credit Cards
  create: all
  match: "**/*"
  templates:
  - credit-cards-guide
- type: directory
  path: content/loans
  label: Loans
  create: all
  match: "**/*"
  templates:
  - loans-guide
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
