---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: ''
sections:
- type: directory
  path: "./site/content"
  label: Pages
  create: all
  match: "*"
- type: directory
  path: "./site/content/free-credit-report"
  label: Free credit report
  create: documents
  match: "**/*"
  templates:
  - credit-report-guide
- type: directory
  path: "./site/content/mortgages"
  label: Mortgages
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/credit-cards"
  label: Credit cards
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/loans"
  label: Loans
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.51
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.51
  preview_output_directory: dist
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.51'
