---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: ''
sections:
- type: directory
  path: "./site/content"
  label: Pages
  create: all
  match: "*"
- type: directory
  path: "./site/content/free-credit-report"
  label: Free credit report
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/mortgages"
  label: Mortgages
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/credit-cards"
  label: Credit cards
  create: all
  match: "**/*"
- type: directory
  path: "./site/content/loans"
  label: Loans
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
